ALTER TABLE backgrounds
ADD COLUMN IF NOT EXISTS price VARCHAR(255);

ALTER TABLE backgrounds 
ADD COLUMN IF NOT EXISTS category VARCHAR(255);

ALTER TABLE backgrounds 
ADD COLUMN IF NOT EXISTS blockchain_tx_hash VARCHAR(255);

ALTER TABLE backgrounds 
ADD COLUMN IF NOT EXISTS blockchain_id VARCHAR(255);

ALTER TABLE backgrounds
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP; 