version: 0.2

phases:
  install:
    commands:
      - echo Installing NPM dependencies
      - npm install
  build:
    commands:
      - echo Compiling smart contracts
      - npm run compile
  post_build:
    commands:
      - echo Build completed

artifacts:
  files:
    - '**/*'
  discard-paths: no